"""Tunable parameters for IC-CISD (Ideal Formation) screening."""

TARGET_WATCHLIST = [
    "ASTS", "TEAM", "INTC", "SMCI", "LULU", "IREN", "ALB", "CRWV",
    "MU", "AMZN", "ORCL", "NOW", "GOOGL", "HOOD", "SOFI", "HIMS",
    "CELH", "NVO", "UNH", "NIO", "DXCM", "RACE", "ZETA", "MARA",
    "SPCX", "MRNA", "AMD", "LLY", "BSP", "NKE", "PYPL", "CAT",
    "APP", "DELL", "AAPL", "PLTR",
]

MIN_BARS_DAILY = 30
MIN_BARS_4H = 30
MIN_BARS_15M = 40
MIN_BARS_5M = 60

HTF_SWEEP_LOOKBACK = 8
SL_BUFFER_TICKS = 0.01
SL_BUFFER_PCT = 0.0005
MIN_RR = 1.5
ENTRY_READY_MIN_RR = 2.0
CISD_TIMING_MAX_PCT = 0.5
USE_CISD_LIMIT_ENTRY = False

YF_PERIOD_DAILY = "730d"
YF_PERIOD_1H = "730d"
YF_PERIOD_15M = "60d"
YF_PERIOD_5M = "30d"

# Legacy — kept for deprecated modules
MIN_BARS_1H = 50
MIN_MARKET_CAP = 10_000_000_000
SWING_LOOKBACK = 3
RR_RATIO = 2.0
USE_VOLUME_FILTER = True
VOL_SMA_LENGTH = 20
USE_ADX_FILTER = False
ADX_THRESHOLD = 20
USE_BODY_FILTER = False
MIN_BODY_RATIO = 0.4
USE_EMA_FILTER = False
EMA_LENGTH = 50
PIVOT_WINDOW = 2
FIB_OTE_RATIO = 0.71
OB_ENTRY_TOLERANCE_PCT = 0.001
SETUP_LOOKBACK = 20
EMA_PERIOD = 20
STRUCTURE_LOOKBACK = 20
RSI_PERIOD = 14
TP_RR_RATIO = 2.0
LTF_INTERVAL = "15m"
